server:
  port: 10006
  servlet:
    context-path: /bank02
  tomcat:
    uri-encoding: UTF-8
  #设置编码为UTF-8

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: db
    active: db
  output:
    ansi:
      enabled: detect
  application:
    name: tx-tcc-bank02

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true