spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vault
    username: root
    password: root
    hikari:
      maximum-pool-size: 500
      minimum-idle: 50
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true