#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.17.13.88:3306/omdmain?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#    test-while-idle: true
#    test-on-borrow: true
#    validation-query: SELECT 1 FROM DUAL
#    time-between-eviction-runs-millis: 300000
#    min-evictable-idle-time-millis: 1800000